ENVIRONMENTS = [
    {
        "id": "cozinha",
        "name": "Cozinha",
        "emoji": "🍳",
        "tasks": [
            "Furo de passagem",
            "Tubulação de água fria",
            "Tubulação de esgoto",
            "Ponto para torneira",
            "Ponto para máquina de lavar louça",
            "Caixas elétricas",
            "Eletrodutos",
            "Fiação",
            "Ponto forno 220 V",
            "Tomadas",
            "Interruptores",
            "Disjuntores",
            "Quadro de distribuição",
            "Contramarco",
            "Esquadria",
            "Vidros da esquadria",
            "Silicone de vedação",
            "Peitoril",
            "Gesso",
            "Sanca de gesso",
            "Porcelanato",
            "Ralo",
            "Rejunte do porcelanato",
            "Soleira",
            "Cantoneiras / sarrafos",
            "Bancada",
            "Tanque",
            "Rejunte da bancada",
            "Rodopia (rodabanca)",
            "Selador",
            "Massa",
            "Pintura",
            "Rodapé",
            "Porta",
            "Dobradiças",
            "Fechadura",
            "Cuba",
            "Torneira",
            "Sifão",
            "Válvula da cuba",
            "Metais",
            "Acabamentos dos registros",
            "Instalação das tomadas",
            "Instalação dos interruptores",
            "Teste dos circuitos",
            "Proteção dos acabamentos",
            "Limpeza pós-obra",
        ],
    },
    {
        "id": "sala",
        "name": "Sala de Estar / Jantar",
        "emoji": "🛋️",
        "tasks": [
            "Caixas elétricas",
            "Fiação",
            "Tomadas",
            "Interruptores",
            "Contramarco",
            "Esquadria",
            "Vidros da esquadria",
            "Silicone de vedação",
            "Porcelanato",
            "Rejunte piso",
            "Selador",
            "Massa",
            "Pintura das paredes e teto",
            "Proteção dos acabamentos",
            "Limpeza pós-obra",
        ],
    },
    {
        "id": "suite_principal",
        "name": "Suíte Principal",
        "emoji": "🛏️",
        "tasks": [
            "Caixas elétricas",
            "Eletrodutos",
            "Fiação",
            "Tomadas",
            "Interruptores",
            "Contramarco",
            "Esquadria",
            "Vidros da esquadria",
            "Silicone de vedação",
            "Gesso",
            "Piso",
            "Rejunte",
            "Rodapé",
            "Selador",
            "Massa",
            "Pintura",
            "Porta",
            "Dobradiças",
            "Fechadura",
            "Proteção dos acabamentos",
            "Limpeza pós-obra",
        ],
    },
    {
        "id": "suite_secundaria",
        "name": "Suíte Secundária",
        "emoji": "🛏️",
        "tasks": [
            "Caixas elétricas",
            "Eletrodutos",
            "Fiação",
            "Tomadas",
            "Interruptores",
            "Contramarco",
            "Esquadria",
            "Vidros da esquadria",
            "Silicone de vedação",
            "Peitoril da janela",
            "Gesso",
            "Piso",
            "Rejunte",
            "Rodapé",
            "Selador",
            "Massa",
            "Pintura",
            "Porta",
            "Dobradiças",
            "Fechadura",
            "Proteção dos acabamentos",
            "Limpeza pós-obra",
        ],
    },
    {
        "id": "banheiro_principal",
        "name": "Banheiro Suíte Principal",
        "emoji": "🚿",
        "tasks": [
            "Furo de passagem",
            "Tubulação de água fria",
            "Tubulação de água quente",
            "Tubulação de esgoto",
            "Ponto para chuveiro",
            "Tomada chuveiro elétrico",
            "Ponto torneira",
            "Caixas elétricas",
            "Iluminação do teto",
            "Ponto do vaso",
            "Contrapiso",
            "Ralo box",
            "Ralo externo",
            "Impermeabilização box",
            "Teste de estanqueidade",
            "Drywall do shaft",
            "Basculante (esquadria)",
            "Peitoril da janela",
            "Forro de gesso",
            "Revestimento",
            "Cantoneira do revestimento",
            "Rejunte",
            "Soleira",
            "Filete",
            "Bancada",
            "Rodopia",
            "Cantoneira / sarrafo",
            "Porta",
            "Alisar da porta",
            "Fechadura",
            "Vaso sanitário",
            "Cuba",
            "Torneira",
            "Sifão",
            "Válvula",
            "Metais",
        ],
    },
    {
        "id": "banheiro_secundario",
        "name": "Banheiro Suíte Secundária",
        "emoji": "🚿",
        "tasks": [
            "Furo de passagem",
            "Tubulação de água fria",
            "Tubulação de água quente",
            "Tubulação de esgoto",
            "Ponto para chuveiro",
            "Tomada chuveiro elétrico",
            "Ponto torneira",
            "Caixas elétricas",
            "Iluminação do teto",
            "Ponto do vaso",
            "Contrapiso",
            "Ralo box",
            "Ralo externo",
            "Impermeabilização box",
            "Teste de estanqueidade",
            "Drywall do shaft",
            "Exaustor (instalação e funcionamento)",
            "Forro de gesso",
            "Revestimento",
            "Cantoneira do revestimento",
            "Rejunte",
            "Soleira",
            "Filete",
            "Bancada",
            "Rodopia",
            "Cantoneira / sarrafo",
            "Porta",
            "Alisar da porta",
            "Fechadura",
            "Vaso sanitário",
            "Cuba",
            "Torneira",
            "Sifão",
            "Válvula",
            "Metais",
        ],
    },
    {
        "id": "varanda",
        "name": "Varanda",
        "emoji": "🌿",
        "tasks": [
            "Ponto de água",
            "Ponto esgoto",
            "Shaft",
            "Caixas elétricas",
            "Fiação",
            "Tomada / interruptor",
            "Contrapiso",
            "Revestimento viga",
            "Revestimento nas paredes",
            "Rejunte parede",
            "Furos do ralo linear",
            "Ralo linear",
            "Piso / porcelanato",
            "Arremate parede piso",
            "Arremate piso",
            "Chapim",
            "Mastique",
            "Cantoneira bancada / sarrafo",
            "Bancada",
            "Rodopia",
            "Rejunte bancada",
            "Forro",
            "Iluminação forro",
        ],
    },
]

STATUS = {
    "N": {"label": "Não Iniciado", "short": "N", "color": "#6b7280", "bg": "#f3f4f6", "border": "#9ca3af"},
    "I": {"label": "Incompleto",   "short": "I", "color": "#1d4ed8", "bg": "#dbeafe", "border": "#60a5fa"},
    "A": {"label": "Ajuste",       "short": "A", "color": "#92400e", "bg": "#fef3c7", "border": "#fbbf24"},
    "C": {"label": "Concluído",    "short": "C", "color": "#15803d", "bg": "#dcfce7", "border": "#4ade80"},
}

APARTMENT_TYPES = ["C", "D", "E", "F", "G"]
NUM_FLOORS = 15
APTS_PER_FLOOR = 27
TOTAL_TASKS = sum(len(e["tasks"]) for e in ENVIRONMENTS)
